name: Posts

on:
  schedule:
    # 08:00 horário de Brasília = 11:00 UTC (Brasília está UTC-3)
    - cron: '0 11 * * *'
  workflow_dispatch:  # Permite execução manual

jobs:
  verificar-elementos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_postsapi.txt
      
      - name: Instalar Google Chrome e ChromeDriver
        uses: browser-actions/setup-chrome@v1
      
      - name: Instalar xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb
      
      - name: Rodar verificação de elementos
        env:
          EMAIL_APP_P: ${{ secrets.EMAIL_APP_P }}
          SENHA_APP_P: ${{ secrets.SENHA_APP_P }}
        run: xvfb-run python alerta_posts.py
